export const GET_SESSIONS_PENDING = 'GET_SESSIONS_PENDING';
export const GET_SESSIONS_SUCCESS = 'GET_SESSIONS_SUCCESS';
export const GET_SESSIONS_ERROR = 'GET_SESSIONS_ERROR';

export const GET_SESSION_BY_ID_PENDING = 'GET_SESSION_BY_ID_PENDING';
export const GET_SESSION_BY_ID_SUCCESS = 'GET_SESSION_BY_ID_SUCCESS';
export const GET_SESSION_BY_ID_ERROR = 'GET_SESSION_BY_ID_ERROR';

export const CREATE_SESSION_PENDING = 'CREATE_SESSION_PENDING';
export const CREATE_SESSION_SUCCESS = 'CREATE_SESSION_SUCCESS';
export const CREATE_SESSION_ERROR = 'CREATE_SESSION_ERROR';

export const UPDATE_SESSION_PENDING = 'UPDATE_SESSION_PENDING';
export const UPDATE_SESSION_SUCCESS = 'UPDATE_SESSION_SUCCESS';
export const UPDATE_SESSION_ERROR = 'UPDATE_SESSION_ERROR';

export const DELETE_SESSION_PENDING = 'DELETE_SESSION_PENDING';
export const DELETE_SESSION_SUCCESS = 'DELETE_SESSION_SUCCESS';
export const DELETE_SESSION_ERROR = 'DELETE_SESSION_ERROR';

export const CLEAN_ERROR = 'CLEAN_ERROR';

export const CLEAN_SELECTED_ITEM = 'CLEAN_SELECTED_ITEM';
