export const GET_INTERVIEWS_PENDING = 'GET_INTERVIEWS_PENDING';
export const GET_INTERVIEWS_SUCCESS = 'GET_INTERVIEWS_SUCCESS';
export const GET_INTERVIEWS_ERROR = 'GET_INTERVIEWS_ERROR';

export const GET_INTERVIEW_BY_ID_PENDING = 'GET_INTERVIEW_BY_ID_PENDING';
export const GET_INTERVIEW_BY_ID_SUCCESS = 'GET_INTERVIEW_BY_ID_SUCCESS';
export const GET_INTERVIEW_BY_ID_ERROR = 'GET_INTERVIEW_BY_ID_ERROR';

export const CREATE_INTERVIEW_PENDING = 'CREATE_INTERVIEW_PENDING';
export const CREATE_INTERVIEW_SUCCESS = 'CREATE_INTERVIEW_SUCCESS';
export const CREATE_INTERVIEW_ERROR = 'CREATE_INTERVIEW_ERROR';

export const UPDATE_INTERVIEW_PENDING = 'UPDATE_INTERVIEW_PENDING';
export const UPDATE_INTERVIEW_SUCCESS = 'UPDATE_INTERVIEW_SUCCESS';
export const UPDATE_INTERVIEW_ERROR = 'UPDATE_INTERVIEW_ERROR';

export const DELETE_INTERVIEW_PENDING = 'DELETE_INTERVIEW_PENDING';
export const DELETE_INTERVIEW_SUCCESS = 'DELETE_INTERVIEW_SUCCESS';
export const DELETE_INTERVIEW_ERROR = 'DELETE_INTERVIEW_ERROR';

export const CLEAN_ERROR = 'CLEAN_ERROR';

export const CLEAN_SELECTED_ITEM = 'CLEAN_SELECTED_ITEM';
