export const GET_APPLICATIONS_PENDING = 'GET_APPLICATIONS_PENDING';
export const GET_APPLICATIONS_SUCCESS = 'GET_APPLICATIONS_SUCCESS';
export const GET_APPLICATIONS_ERROR = 'GET_APPLICATIONS_ERROR';

export const GET_APPLICATION_BY_ID_PENDING = 'GET_APPLICATION_BY_ID_PENDING';
export const GET_APPLICATION_BY_ID_SUCCESS = 'GET_APPLICATION_BY_ID_SUCCESS';
export const GET_APPLICATION_BY_ID_ERROR = 'GET_APPLICATION_BY_ID_ERROR';

export const CREATE_APPLICATION_PENDING = 'CREATE_APPLICATION_PENDING';
export const CREATE_APPLICATION_SUCCESS = 'CREATE_APPLICATION_SUCCESS';
export const CREATE_APPLICATION_ERROR = 'CREATE_APPLICATION_ERROR';

export const UPDATE_APPLICATION_PENDING = 'UPDATE_APPLICATION_PENDING';
export const UPDATE_APPLICATION_SUCCESS = 'UPDATE_APPLICATION_SUCCESS';
export const UPDATE_APPLICATION_ERROR = 'UPDATE_APPLICATION_ERROR';

export const DELETE_APPLICATION_PENDING = 'DELETE_APPLICATION_PENDING';
export const DELETE_APPLICATION_SUCCESS = 'DELETE_APPLICATION_SUCCESS';
export const DELETE_APPLICATION_ERROR = 'DELETE_APPLICATION_ERROR';

export const CLEAN_ERROR = 'CLEAN_ERROR';

export const CLEAN_SELECTED_ITEM = 'CLEAN_SELECTED_ITEM';
