export const GET_POSITIONS_PENDING = 'GET_POSITIONS_PENDING';
export const GET_POSITIONS_SUCCESS = 'GET_POSITIONS_SUCCESS';
export const GET_POSITIONS_ERROR = 'GET_POSITIONS_ERROR';

export const GET_POSITION_BY_ID_PENDING = 'GET_POSITION_BY_ID_PENDING';
export const GET_POSITION_BY_ID_SUCCESS = 'GET_POSITION_BY_ID_SUCCESS';
export const GET_POSITION_BY_ID_ERROR = 'GET_POSITION_BY_ID_ERROR';

export const CREATE_POSITION_PENDING = 'CREATE_POSITION_PENDING';
export const CREATE_POSITION_SUCCESS = 'CREATE_POSITION_SUCCESS';
export const CREATE_POSITION_ERROR = 'CREATE_POSITION_ERROR';

export const UPDATE_POSITION_PENDING = 'UPDATE_POSITION_PENDING';
export const UPDATE_POSITION_SUCCESS = 'UPDATE_POSITION_SUCCESS';
export const UPDATE_POSITION_ERROR = 'UPDATE_POSITION_ERROR';

export const DELETE_POSITION_PENDING = 'DELETE_POSITION_PENDING';
export const DELETE_POSITION_SUCCESS = 'DELETE_POSITION_SUCCESS';
export const DELETE_POSITION_ERROR = 'DELETE_POSITION_ERROR';

export const CLEAN_ERROR = 'CLEAN_ERROR';

export const CLEAN_SELECTED_ITEM = 'CLEAN_SELECTED_ITEM';
