export const GET_PROFILES_PENDING = 'GET_PROFILES_PENDING';
export const GET_PROFILES_SUCCESS = 'GET_PROFILES_SUCCESS';
export const GET_PROFILES_ERROR = 'GET_PROFILES_ERROR';

export const GET_PROFILE_BY_ID_PENDING = 'GET_PROFILE_BY_ID_PENDING';
export const GET_PROFILE_BY_ID_SUCCESS = 'GET_PROFILE_BY_ID_SUCCESS';
export const GET_PROFILE_BY_ID_ERROR = 'GET_PROFILE_BY_ID_ERROR';

export const CREATE_PROFILE_PENDING = 'CREATE_PROFILE_PENDING';
export const CREATE_PROFILE_SUCCESS = 'CREATE_PROFILE_SUCCESS';
export const CREATE_PROFILE_ERROR = 'CREATE_PROFILE_ERROR';

export const UPDATE_PROFILE_PENDING = 'UPDATE_PROFILE_PENDING';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';

export const DELETE_PROFILE_PENDING = 'DELETE_PROFILE_PENDING';
export const DELETE_PROFILE_SUCCESS = 'DELETE_PROFILE_SUCCESS';
export const DELETE_PROFILE_ERROR = 'DELETE_PROFILE_ERROR';

export const CLEAN_ERROR = 'CLEAN_ERROR';
